const PAYMENT_STATUS = Object.freeze({
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    PAID: "PAID",
    FAILED: "FAILED",
    REFUNDED: "REFUNDED",
    CANCELLED: "CANCELLED",
});

module.exports = { PAYMENT_STATUS };